import type {
  LocalBusiness,
  LocalBusinessesSectionContent,
} from "@/types";

export const LOCAL_BUSINESSES_SECTION = {
  eyebrow: "Lokale bedrijven die we helpen",
  titleLead: "De juiste website voor",
  titleEm: "jouw lokale bedrijf.",
  sub: "Niet zeker welke website jij nodig hebt? Zoek hieronder jouw branche — wij weten al wat werkt en bouwen het voor je.",
  loadMoreLabel: "Toon meer branches",
  loadLessLabel: "Toon minder",
  searchPlaceholder: "Zoek jouw branche… (bijv. kapper, restaurant, makelaar)",
  searchAriaLabel: "Zoek op branche",
  clearSearchLabel: "Zoekopdracht wissen",
  allGroupsLabel: "Alle",
  filterAriaLabel: "Filter branches op categorie",
  resultsLabel: "{count} branches",
  emptyTitle: "Geen branche gevonden",
  emptyBody:
    "We vonden niets voor “{query}”. Beschrijf jouw bedrijf in een berichtje — we bouwen ook websites voor branches die hier nog niet staan.",
  emptyCtaLabel: "Beschrijf jouw branche",
  emptyCtaProjectType: "Website voor mijn branche",
} as const satisfies LocalBusinessesSectionContent;

/** Display order of the group-filter chips (after the "Alle" chip). */
export const LOCAL_BUSINESS_GROUPS = [
  "Auto",
  "Vastgoed",
  "Horeca & food",
  "Beauty & wellness",
  "Zakelijke diensten",
  "Huis & klus",
  "Retail",
  "Fitness",
  "Onderwijs",
  "Zorg",
  "Overig",
] as const;

export const LOCAL_BUSINESSES = [
  // ── Auto ──────────────────────────────────────────────────────────────
  {
    slug: "car-wash",
    icon: "carWash",
    group: "Auto",
    title: "Autowasstraat",
    description:
      "Toon pakketten, prijzen en openingstijden en laat klanten een wasbeurt online inplannen — vol rooster, minder wachtrij.",
    badge: "Populair",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor autowasstraat",
    keywords: ["car wash", "autowas", "wasstraat", "auto", "carwash"],
    image: "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een auto in een moderne wasstraat met schuim en borstels.",
  },
  {
    slug: "auto-repair",
    icon: "autoRepair",
    group: "Auto",
    title: "Autoreparatiebedrijf",
    description:
      "Diensten, certificeringen, openingstijden, locatie en een snel-offerteformulier. Verdien vertrouwen voordat ze de garage in lopen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor autoreparatiebedrijf",
    keywords: ["auto repair", "garage", "monteur", "apk", "werkplaats"],
    image: "https://images.unsplash.com/photo-1618312980096-873bd19759a0?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een monteur aan het werk in een garage met auto's op heffers.",
  },
  {
    slug: "car-detailing",
    icon: "carDetailing",
    group: "Auto",
    title: "Car detailing",
    description:
      "Voor/na-foto's, pakketten en online boekingen — laat de glans van jouw werk de verkoop doen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor car detailing",
    keywords: ["car detailing", "detailing", "poetsen", "auto", "coating"],
    image: "https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf0?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een glanzend gepoetste auto na een detailing-behandeling.",
  },
  {
    slug: "auto-dealer",
    icon: "autoDealer",
    group: "Auto",
    title: "Autodealer",
    description:
      "Een doorzoekbare voorraad met foto's, prijzen en een proefrit-aanvraag — jouw showroom, 24/7 online.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor autodealer",
    keywords: ["auto dealer", "occasions", "showroom", "autobedrijf", "garage"],
    image: "https://images.unsplash.com/photo-1574023240744-64c47c8c0676?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een autoshowroom met glanzende auto's onder heldere verlichting.",
  },
  {
    slug: "driving-school",
    icon: "drivingSchool",
    group: "Auto",
    title: "Rijschool",
    description:
      "Pakketten, slagingspercentage, instructeurs en een proefles-aanmelding — gemaakt om jouw agenda vol te krijgen.",
    badge: "Voor lokale groei",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor rijschool",
    keywords: ["driving school", "rijles", "rijbewijs", "rijinstructeur"],
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een lesauto met daklogo op een rustige oefenweg.",
  },

  // ── Vastgoed ──────────────────────────────────────────────────────────
  {
    slug: "real-estate",
    icon: "realEstate",
    group: "Vastgoed",
    title: "Makelaar",
    description:
      "Een verzorgde galerij met aanbod, bezichtigingsaanvragen en waardebepaling — vertrouwen wekken vanaf de eerste klik.",
    badge: "Populair",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor makelaar",
    keywords: ["real estate", "makelaar", "vastgoed", "huizen", "woning"],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een moderne woning met een 'te koop'-bord van een makelaar.",
  },
  {
    slug: "property-management",
    icon: "propertyManagement",
    group: "Vastgoed",
    title: "Vastgoedbeheer",
    description:
      "Toon diensten, portfolio en een huurder-/eigenaarsportaal — professioneel beheer dat zichzelf verkoopt.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor vastgoedbeheer",
    keywords: ["property management", "vastgoedbeheer", "vve", "beheer"],
    image: "https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een appartementencomplex met strakke gevels en balkons.",
  },
  {
    slug: "rental-agency",
    icon: "rentalAgency",
    group: "Vastgoed",
    title: "Verhuurmakelaar",
    description:
      "Beschikbaar aanbod, filters op prijs en wijk en directe bezichtigingsaanvragen — huurders vinden sneller hun plek.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor verhuurmakelaar",
    keywords: ["rental", "verhuur", "huurwoning", "appartement", "kamer"],
    image: "https://images.unsplash.com/photo-1722487631997-cf1e0f92c2c4?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een sleutel voor een appartement met een licht interieur op de achtergrond.",
  },
  {
    slug: "commercial-property",
    icon: "commercialProperty",
    group: "Vastgoed",
    title: "Bedrijfsruimte",
    description:
      "Kantoren, winkels en loodsen met plattegronden, oppervlakte en een aanvraagformulier — voor ondernemers die ruimte zoeken.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor bedrijfsruimte",
    keywords: ["commercial property", "bedrijfsruimte", "kantoor", "loods", "winkelpand"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een modern kantoorpand met grote glaspartijen.",
  },

  // ── Horeca & food ─────────────────────────────────────────────────────
  {
    slug: "restaurant-cafe",
    icon: "restaurant",
    group: "Horeca & food",
    title: "Restaurant / Café",
    description:
      "Menu, foto's, reserveringen, Google Maps en WhatsApp voor last-minute tafels. Alles wat een hongerige bezoeker nodig heeft.",
    badge: "Populair",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor restaurant of café",
    keywords: ["restaurant", "cafe", "eetcafe", "menu", "reserveren", "horeca"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een warm restaurantinterieur met gedekte tafels en sfeerverlichting.",
  },
  {
    slug: "coffee-bar",
    icon: "coffeeBar",
    group: "Horeca & food",
    title: "Koffiebar",
    description:
      "Een sfeervolle site met menu, openingstijden, loyaliteitsacties en bestellen vooraf — zodat de ochtendrij blijft groeien.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor koffiebar",
    keywords: ["coffee", "koffiebar", "koffie", "barista", "cafe", "lunchroom"],
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een knusse koffiebar met een espressomachine en houten toonbank.",
  },
  {
    slug: "bakery",
    icon: "bakery",
    group: "Horeca & food",
    title: "Bakkerij & patisserie",
    description:
      "Een warme site met dagmenu, bestellingen voor taarten op maat, openingstijden en afhaalinformatie — eetlust gegarandeerd.",
    badge: "Starterswebsite",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor bakkerij",
    keywords: ["bakery", "bakkerij", "patisserie", "taart", "brood", "banketbakker"],
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Vers ambachtelijk brood en gebak in een bakkerij.",
  },
  {
    slug: "fast-food",
    icon: "fastFood",
    group: "Horeca & food",
    title: "Snackbar / fastfood",
    description:
      "Menu met foto's, online bestellen en afhalen, bezorgzones en openingstijden — klanten bestellen voordat de honger toeslaat.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor snackbar of fastfood",
    keywords: ["fast food", "snackbar", "cafetaria", "afhalen", "bezorgen", "friet"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een verse hamburger met friet op een toonbank.",
  },
  {
    slug: "catering",
    icon: "catering",
    group: "Horeca & food",
    title: "Catering",
    description:
      "Toon arrangementen, eerdere events en een offerte-aanvraag — van borrel tot bruiloft, in een paar klikken geboekt.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor catering",
    keywords: ["catering", "buffet", "bedrijfscatering", "events", "feest"],
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een rijk gevuld cateringbuffet met hapjes en gerechten.",
  },

  // ── Beauty & wellness ─────────────────────────────────────────────────
  {
    slug: "hair-salon",
    icon: "hairSalon",
    group: "Beauty & wellness",
    title: "Kapsalon",
    description:
      "Toon diensten, prijzen, openingstijden en je locatie op de kaart — klanten kunnen direct online of via WhatsApp boeken.",
    badge: "Populair",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor kapsalon",
    keywords: ["hair salon", "kapper", "kapsalon", "haar", "knippen"],
    image: "https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een lichte kapsalon met spiegels en moderne stoelen.",
  },
  {
    slug: "barber-shop",
    icon: "barbershop",
    group: "Beauty & wellness",
    title: "Barbershop",
    description:
      "Een stoere site met diensten, prijzen, openingstijden en direct boeken — gebouwd om je stoelen vol te houden.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor barbershop",
    keywords: ["barbershop", "barber", "kapper", "baard", "heren", "knippen"],
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een moderne barbershop met leren stoelen en warme verlichting.",
  },
  {
    slug: "beauty-salon",
    icon: "beautySalon",
    group: "Beauty & wellness",
    title: "Schoonheidssalon",
    description:
      "Een elegante site met behandelingen, voor/na-foto's, online reserveren en cadeaubonnen voor vaste klanten.",
    badge: "Voor lokale groei",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor schoonheidssalon",
    keywords: ["beauty salon", "schoonheidssalon", "huidverzorging", "beauty", "gezicht"],
    image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een lichte, elegante schoonheidssalon met behandelplekken.",
  },
  {
    slug: "spa-wellness",
    icon: "spa",
    group: "Beauty & wellness",
    title: "Spa & wellness",
    description:
      "Een rustgevende site met arrangementen, sfeerbeelden, cadeaubonnen en online reserveren — ontspanning begint bij de eerste klik.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor spa of wellness",
    keywords: ["spa", "wellness", "massage", "sauna", "ontspanning"],
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een serene spa met kaarsen, handdoeken en zacht licht.",
  },
  {
    slug: "nail-salon",
    icon: "nailSalon",
    group: "Beauty & wellness",
    title: "Nagelstudio",
    description:
      "Een stijlvolle galerij met je beste sets, prijzen en online boeken — laat je werk de afspraken binnenhalen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor nagelstudio",
    keywords: ["nail salon", "nagelstudio", "nagels", "manicure", "gelnagels"],
    image: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Verzorgde handen met fraai gelakte nagels in een nagelstudio.",
  },

  // ── Zakelijke diensten ────────────────────────────────────────────────
  {
    slug: "lawyer",
    icon: "lawyer",
    group: "Zakelijke diensten",
    title: "Advocaat",
    description:
      "Rechtsgebieden, teamprofielen, reviews en een vertrouwelijk contactformulier — autoriteit en vertrouwen vanaf het eerste bezoek.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor advocaat",
    keywords: ["lawyer", "advocaat", "juridisch", "advocatenkantoor", "recht"],
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een verzorgd advocatenkantoor met boeken en een bureau.",
  },
  {
    slug: "accountant",
    icon: "accountant",
    group: "Zakelijke diensten",
    title: "Accountant",
    description:
      "Diensten, branches en een afspraak-aanvraag, helder uitgelegd — voor ondernemers die rust in hun cijfers zoeken.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor accountant",
    keywords: ["accountant", "boekhouder", "administratie", "belasting", "boekhouding"],
    image: "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een bureau met financiële documenten, rekenmachine en laptop.",
  },
  {
    slug: "consultant",
    icon: "consultant",
    group: "Zakelijke diensten",
    title: "Consultant",
    description:
      "Een scherpe site met jouw aanpak, cases en resultaten — positioneer je als de expert die opdrachtgevers willen inhuren.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor consultant",
    keywords: ["consultant", "adviseur", "consultancy", "strategie", "coach"],
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een zakelijk overleg met laptops en een whiteboard.",
  },
  {
    slug: "insurance-agency",
    icon: "insurance",
    group: "Zakelijke diensten",
    title: "Verzekeringen",
    description:
      "Producten, helder uitgelegd, met vergelijkingen en een offerte-aanvraag — vertrouwen en duidelijkheid in één site.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor verzekeringskantoor",
    keywords: ["insurance", "verzekering", "verzekeringen", "assurantie", "tussenpersoon"],
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een verzekeringsadviseur die documenten met een klant bespreekt.",
  },
  {
    slug: "notary",
    icon: "notary",
    group: "Zakelijke diensten",
    title: "Notaris",
    description:
      "Diensten rond familie, wonen en onderneming, met heldere tarieven en een afspraakaanvraag — vertrouwen op elke pagina.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor notaris",
    keywords: ["notary", "notaris", "akte", "testament", "notariskantoor"],
    image: "https://images.unsplash.com/photo-1603796846097-bee99e4a601f?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een notaristafel met documenten, pen en een stempel.",
  },

  // ── Huis & klus ───────────────────────────────────────────────────────
  {
    slug: "plumber",
    icon: "plumber",
    group: "Huis & klus",
    title: "Loodgieter",
    description:
      "Diensten, werkgebied, spoednummer en een snelle offerte — gevonden worden op het moment dat het echt nodig is.",
    badge: "Voor lokale groei",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor loodgieter",
    keywords: ["plumber", "loodgieter", "lekkage", "sanitair", "cv", "installateur"],
    image: "https://images.unsplash.com/photo-1676210133055-eab6ef033ce3?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een loodgieter die met gereedschap aan een leiding werkt.",
  },
  {
    slug: "electrician",
    icon: "electrician",
    group: "Huis & klus",
    title: "Elektricien",
    description:
      "Diensten, certificeringen, werkgebied en een offerteformulier — duidelijk en betrouwbaar voor elke klus.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor elektricien",
    keywords: ["electrician", "elektricien", "elektra", "installateur", "groepenkast"],
    image: "https://images.unsplash.com/photo-1682345262055-8f95f3c513ea?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een elektricien die bekabeling in een meterkast aansluit.",
  },
  {
    slug: "cleaning-service",
    icon: "cleaningService",
    group: "Huis & klus",
    title: "Schoonmaakbedrijf",
    description:
      "Diensten voor particulier en zakelijk, werkgebied en een snelle offerte-aanvraag — vertrouwen in een vlekkeloze site.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor schoonmaakbedrijf",
    keywords: ["cleaning", "schoonmaak", "schoonmaakbedrijf", "poetsen", "glazenwasser"],
    image: "https://images.unsplash.com/photo-1740657254989-42fe9c3b8cce?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een schoonmaker met materiaal in een fris, schoon interieur.",
  },
  {
    slug: "pest-control",
    icon: "pestControl",
    group: "Huis & klus",
    title: "Ongediertebestrijding",
    description:
      "Diensten, werkgebied, spoedhulp en een aanvraagformulier — discreet en deskundig, precies wanneer het nodig is.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor ongediertebestrijding",
    keywords: ["pest control", "ongedierte", "bestrijding", "muizen", "wespen", "plaagdier"],
    image: "https://images.unsplash.com/photo-1581578017093-cd30fce4eeb7?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een specialist in beschermende kleding tijdens een bestrijdingsklus.",
  },
  {
    slug: "landscaping",
    icon: "landscaping",
    group: "Huis & klus",
    title: "Hovenier",
    description:
      "Een groene portfolio met aanleg, onderhoud en ontwerp plus een offerte-aanvraag — laat je vakwerk de klus binnenhalen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor hovenier",
    keywords: ["landscaping", "hovenier", "tuin", "tuinaanleg", "tuinonderhoud"],
    image: "https://images.unsplash.com/photo-1734079692160-fcbe4be6ab96?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een fraai aangelegde tuin met bestrating en beplanting.",
  },
  {
    slug: "painter",
    icon: "painter",
    group: "Huis & klus",
    title: "Schildersbedrijf",
    description:
      "Voor/na-projecten, diensten binnen en buiten en een offerte-aanvraag — overtuig met strak afgewerkt werk.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor schildersbedrijf",
    keywords: ["painter", "schilder", "schildersbedrijf", "verven", "behangen"],
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een schilder met roller die een muur strak afwerkt.",
  },
  {
    slug: "construction",
    icon: "construction",
    group: "Huis & klus",
    title: "Bouwbedrijf",
    description:
      "Projecten, specialismen, reviews en een offerte-aanvraag — vakmanschap dat overtuigt voordat de eerste steen ligt.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor bouwbedrijf",
    keywords: ["construction", "bouwbedrijf", "aannemer", "verbouwing", "bouw", "klusbedrijf"],
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een bouwplaats met vakmensen en materiaal in aanbouw.",
  },

  // ── Retail ────────────────────────────────────────────────────────────
  {
    slug: "clothing-store",
    icon: "clothingStore",
    group: "Retail",
    title: "Kledingwinkel",
    description:
      "Een strakke lookbook met nieuwe collecties, openingstijden en bestellen via WhatsApp — gebouwd om lokale klanten binnen te halen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor kledingwinkel",
    keywords: ["clothing", "kleding", "kledingwinkel", "mode", "boutique", "fashion"],
    image: "https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een stijlvolle kledingwinkel met rekken vol kleding.",
  },
  {
    slug: "mens-clothing",
    icon: "mensFashion",
    group: "Retail",
    title: "Herenmode",
    description:
      "Een strakke catalogus met nieuwe collecties, maten, adres en bestellen via WhatsApp — gebouwd om lokale klanten binnen te halen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor herenmodewinkel",
    keywords: ["mens fashion", "herenmode", "heren", "mode", "kleding", "pak"],
    image: "https://images.unsplash.com/photo-1694947563422-d4b401588d1d?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een herenmodewinkel met rijen hangende overhemden en jasjes.",
  },
  {
    slug: "electronics-store",
    icon: "electronicsStore",
    group: "Retail",
    title: "Elektronicawinkel",
    description:
      "Een overzichtelijke catalogus met voorraad, prijzen, reparaties en advies — klanten vinden je voordat ze online bestellen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor elektronicawinkel",
    keywords: ["electronics", "elektronica", "telefoonwinkel", "reparatie", "gadgets"],
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een elektronicawinkel met smartphones en gadgets in de vitrine.",
  },
  {
    slug: "furniture-store",
    icon: "furnitureStore",
    group: "Retail",
    title: "Meubelwinkel",
    description:
      "Een warme galerij met collecties, sfeerbeelden, maatwerk en bezorginfo — inspireer bezoekers en breng ze naar de winkel.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor meubelwinkel",
    keywords: ["furniture", "meubels", "meubelwinkel", "interieur", "wonen", "bank"],
    image: "https://images.unsplash.com/photo-1634712282287-14ed57b9cc89?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een ingerichte meubelwinkel met banken en kasten.",
  },
  {
    slug: "supermarket",
    icon: "supermarket",
    group: "Retail",
    title: "Supermarkt / Buurtwinkel",
    description:
      "Toon wekelijkse aanbiedingen, verse aanvoer, bezorgzones en contactgegevens — zodat buren jou vinden voor hun boodschappen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor supermarkt",
    keywords: ["supermarket", "supermarkt", "buurtwinkel", "grocery", "boodschappen", "markt"],
    image: "https://images.unsplash.com/photo-1628102491629-778571d893a3?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een buurtsupermarkt met verse groenten en fruit in de uitstalling.",
  },
  {
    slug: "jewelry",
    icon: "jewelry",
    group: "Retail",
    title: "Juwelier",
    description:
      "Een verfijnde galerij met collecties, maatwerk, reparaties en afspraken — elegantie die je vakwerk laat schitteren.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor juwelier",
    keywords: ["jewelry", "juwelier", "sieraden", "horloges", "goud", "ringen"],
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een vitrine met glinsterende sieraden en horloges.",
  },
  {
    slug: "flower-shop",
    icon: "flowerShop",
    group: "Retail",
    title: "Bloemenwinkel",
    description:
      "Een mooie galerij met boeketten, bezorgzones, gelegenheidsmenu's (bruiloft, verjaardag, condoleance) en bestellen via WhatsApp.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor bloemenzaak",
    keywords: ["flower shop", "bloemist", "bloemenwinkel", "boeket", "flowers", "florist"],
    image: "https://images.unsplash.com/photo-1589244159943-460088ed5c92?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een bloemenwinkel vol met verse boeketten en arrangementen.",
  },

  // ── Fitness ───────────────────────────────────────────────────────────
  {
    slug: "gym",
    icon: "gym",
    group: "Fitness",
    title: "Sportschool / Fitness",
    description:
      "Lesrooster, trainersprofielen, abonnementen en gratis proefles-aanmelding — gemaakt om jouw ochtendlessen vol te krijgen.",
    badge: "Voor lokale groei",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor sportschool",
    keywords: ["gym", "sportschool", "fitness", "krachttraining", "abonnement"],
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een ruime fitnesszaal met fitnessapparatuur en natuurlijk licht.",
  },
  {
    slug: "yoga-studio",
    icon: "yogaStudio",
    group: "Fitness",
    title: "Yogastudio",
    description:
      "Een rustige site met rooster, docenten, proefles en online inschrijven — breng nieuwe leden moeiteloos op de mat.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor yogastudio",
    keywords: ["yoga", "yogastudio", "pilates", "meditatie", "studio"],
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een serene yogastudio met matten en zacht daglicht.",
  },
  {
    slug: "personal-trainer",
    icon: "personalTrainer",
    group: "Fitness",
    title: "Personal trainer",
    description:
      "Toon resultaten, programma's, reviews en een intake-aanvraag — overtuig nieuwe klanten om met jou te starten.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor personal trainer",
    keywords: ["personal trainer", "pt", "coach", "fitness", "training", "afvallen"],
    image: "https://images.unsplash.com/photo-1648542036561-e1d66a5ae2b1?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een personal trainer die een client begeleidt bij een oefening.",
  },

  // ── Onderwijs ─────────────────────────────────────────────────────────
  {
    slug: "school",
    icon: "school",
    group: "Onderwijs",
    title: "School",
    description:
      "Een heldere site met onderwijsvisie, team, aanmeldingen en nieuws — vertrouwen voor ouders, overzicht voor leerlingen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor school",
    keywords: ["school", "onderwijs", "basisschool", "middelbare school", "aanmelden"],
    image: "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een licht klaslokaal met tafels en een schoolbord.",
  },
  {
    slug: "language-center",
    icon: "languageCenter",
    group: "Onderwijs",
    title: "Talenschool",
    description:
      "Cursussen, niveaus, roosters en online inschrijven — voor iedereen die snel een nieuwe taal wil leren.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor talenschool",
    keywords: ["language", "talenschool", "taalcursus", "engels", "inburgering", "les"],
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een taalles met cursisten en een docent voor een bord.",
  },
  {
    slug: "training-center",
    icon: "trainingCenter",
    group: "Onderwijs",
    title: "Trainingscentrum",
    description:
      "Een overzichtelijke site met trainingen, data, certificaten en online aanmelden — vol cursussen, minder administratie.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor trainingscentrum",
    keywords: ["training", "trainingscentrum", "cursus", "opleiding", "workshop", "certificaat"],
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een seminarruimte met deelnemers en een presentatiescherm.",
  },

  // ── Zorg ──────────────────────────────────────────────────────────────
  {
    slug: "clinic",
    icon: "clinic",
    group: "Zorg",
    title: "Huisartsenpraktijk",
    description:
      "Openingstijden, online afspraken, herhaalrecepten en heldere patiënteninfo — een rustige, professionele site die zorg toegankelijk maakt.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor huisartsenpraktijk",
    keywords: ["clinic", "huisarts", "praktijk", "kliniek", "doctor", "zorg"],
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een nette spreekkamer in een huisartsenpraktijk.",
  },
  {
    slug: "pharmacy",
    icon: "pharmacy",
    group: "Zorg",
    title: "Apotheek",
    description:
      "Openingstijden, recept-aanvragen via WhatsApp, locatie en vertrouwenwekkende info — een rustige, professionele site voor jouw patiënten.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor apotheek",
    keywords: ["pharmacy", "apotheek", "medicijnen", "recept", "drogist"],
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een schone, moderne apotheekbalie met producten in de schappen.",
  },
  {
    slug: "physiotherapy",
    icon: "physiotherapy",
    group: "Zorg",
    title: "Fysiotherapie",
    description:
      "Behandelingen, specialisaties, vergoedingen en online afspraken — voor patiënten die snel en vertrouwd geholpen willen worden.",
    badge: "Voor lokale groei",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor fysiotherapie",
    keywords: ["physiotherapy", "fysiotherapie", "fysio", "manuele therapie", "revalidatie"],
    image: "https://images.unsplash.com/photo-1645005512968-0c1fe99f0093?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een fysiotherapeut die een patiënt behandelt in een praktijk.",
  },
  {
    slug: "veterinary",
    icon: "veterinary",
    group: "Zorg",
    title: "Dierenarts",
    description:
      "Diensten, spoedinfo, online afspraken en geruststellende uitleg — zorg waar baasjes hun huisdier met een gerust hart naartoe brengen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor dierenarts",
    keywords: ["veterinary", "dierenarts", "dierenkliniek", "huisdier", "vet"],
    image: "https://images.unsplash.com/photo-1654895716780-b4664497420d?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een dierenarts die een hond onderzoekt in een behandelkamer.",
  },
  {
    slug: "dentist",
    icon: "dentist",
    group: "Zorg",
    title: "Tandartspraktijk",
    description:
      "Behandelingen, tarieven, online afspraken en heldere patiënteninfo — vertrouwen wekken nog voor de eerste controle.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor tandartspraktijk",
    keywords: ["dentist", "tandarts", "tandartspraktijk", "mondzorg", "gebit", "kliniek"],
    image: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een moderne, schone behandelstoel in een tandartspraktijk.",
  },

  // ── Overig ────────────────────────────────────────────────────────────
  {
    slug: "photographer",
    icon: "photographer",
    group: "Overig",
    title: "Fotograaf",
    description:
      "Een visueel portfolio met series, pakketten en een boekingsaanvraag — laat je beelden de opdrachten binnenhalen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor fotograaf",
    keywords: ["photographer", "fotograaf", "fotografie", "shoot", "studio", "bruiloft"],
    image: "https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een fotograaf met camera in een studio met belichting.",
  },
  {
    slug: "travel-agency",
    icon: "travelAgency",
    group: "Overig",
    title: "Reisbureau",
    description:
      "Bestemmingen, arrangementen, reviews en een offerte-aanvraag — inspireer bezoekers en zet dromen om in boekingen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor reisbureau",
    keywords: ["travel", "reisbureau", "reizen", "vakantie", "tickets", "rondreis"],
    image: "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een wereldkaart met reisdocumenten en een koffer.",
  },
  {
    slug: "pet-store",
    icon: "petStore",
    group: "Overig",
    title: "Dierenwinkel / trimsalon",
    description:
      "Een vrolijke site met assortiment, trimafspraken, openingstijden en advies — alles voor het huisdier op één plek.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor dierenwinkel of trimsalon",
    keywords: ["pet store", "dierenwinkel", "trimsalon", "huisdier", "dierenspeciaalzaak", "grooming"],
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een dierenwinkel met voer, speelgoed en benodigdheden in de schappen.",
  },
  {
    slug: "childcare",
    icon: "childcare",
    group: "Overig",
    title: "Kinderopvang",
    description:
      "Een warme site met groepen, dagindeling, tarieven en een rondleidingsaanvraag — vertrouwen voor ouders vanaf het eerste bezoek.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor kinderopvang",
    keywords: ["childcare", "kinderopvang", "kinderdagverblijf", "bso", "peuters", "daycare"],
    image: "https://images.unsplash.com/photo-1578349035260-9f3d4042f1f7?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een vrolijke, kleurrijke ruimte voor kinderopvang met speelgoed.",
  },
  {
    slug: "tattoo-studio",
    icon: "tattooStudio",
    group: "Overig",
    title: "Tattooshop",
    description:
      "Een stoere portfolio met artiesten, stijlen, reviews en een ontwerp-aanvraag — laat je werk de afspraken vullen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor tattooshop",
    keywords: ["tattoo", "tattooshop", "tatoeage", "tattoo studio", "piercing", "artist"],
    image: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een professionele tattoostudio met werkplek en flash-art aan de muur.",
  },

  // ── Extra branches (>=6 per filter) ───────────────────────────────────
  {
    slug: "tire-service",
    icon: "tireService",
    group: "Auto",
    title: "Bandenservice",
    description:
      "Toon je merken, bandenopslag, prijzen en een afspraak voor wissel of reparatie — klaar voor het seizoen, zonder wachtrij aan de balie.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor bandenservice",
    keywords: ["tire", "banden", "bandenservice", "bandenwissel", "velgen", "apk"],
    image: "https://images.unsplash.com/photo-1571335746824-742511d49bce?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Rijen autobanden in een professionele bandenservice.",
  },
  {
    slug: "mortgage-advisor",
    icon: "mortgageAdvisor",
    group: "Vastgoed",
    title: "Hypotheekadviseur",
    description:
      "Diensten, werkwijze en een vrijblijvend adviesgesprek, helder uitgelegd — vertrouwen opbouwen voordat klanten hun grootste aankoop doen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor hypotheekadviseur",
    keywords: ["mortgage", "hypotheek", "hypotheekadviseur", "hypotheekadvies", "financieel advies"],
    image: "https://images.unsplash.com/photo-1672380135241-c024f7fbfa13?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een adviseur die een hypotheekgesprek voert aan een bureau.",
  },
  {
    slug: "home-inspector",
    icon: "homeInspector",
    group: "Vastgoed",
    title: "Woningtaxateur",
    description:
      "Toon je werkgebied, taxatietypes en een snelle aanvraag voor een gevalideerd rapport — duidelijkheid voor kopers, verkopers en geldverstrekkers.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor woningtaxateur",
    keywords: ["appraiser", "taxateur", "woningtaxatie", "taxatierapport", "nwwi", "waardebepaling"],
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een taxateur met klembord die een woning beoordeelt.",
  },
  {
    slug: "ice-cream-shop",
    icon: "iceCreamShop",
    group: "Horeca & food",
    title: "IJssalon",
    description:
      "Een vrolijke site met smaken van de dag, openingstijden, seizoensacties en je locatie op de kaart — zodat de rij voor de deur blijft groeien.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor ijssalon",
    keywords: ["ice cream", "ijssalon", "ijs", "gelato", "schepijs", "softijs"],
    image: "https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Kleurrijke bollen schepijs in een ijssalonvitrine.",
  },
  {
    slug: "pedicure",
    icon: "pedicure",
    group: "Beauty & wellness",
    title: "Pedicure",
    description:
      "Een verzorgde site met behandelingen, tarieven, online boeken en uitleg over medische voetzorg — vertrouwen vanaf de eerste klik.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor pedicure",
    keywords: ["pedicure", "voetverzorging", "voetzorg", "medisch pedicure", "voeten"],
    image: "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een pedicurebehandeling in een verzorgde salon.",
  },
  {
    slug: "marketing-agency",
    icon: "marketingAgency",
    group: "Zakelijke diensten",
    title: "Marketingbureau",
    description:
      "Een scherpe site met diensten, cases en resultaten — positioneer je als het bureau dat merken laat groeien en vraag een kennismaking aan.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor marketingbureau",
    keywords: ["marketing", "marketingbureau", "reclamebureau", "online marketing", "branding", "seo"],
    image: "https://images.unsplash.com/photo-1582005450386-52b25f82d9bb?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een marketingteam dat samen aan een campagne werkt.",
  },
  {
    slug: "dance-studio",
    icon: "danceStudio",
    group: "Fitness",
    title: "Dansschool",
    description:
      "Een energieke site met lesrooster, stijlen, docenten en een gratis proefles — breng nieuwe dansers moeiteloos de zaal in.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor dansschool",
    keywords: ["dance", "dansschool", "dansstudio", "dansles", "ballet", "streetdance"],
    image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Dansers in een ruime dansstudio met spiegelwand.",
  },
  {
    slug: "martial-arts",
    icon: "martialArts",
    group: "Fitness",
    title: "Vechtsportschool",
    description:
      "Toon disciplines, lesrooster, trainers en een gratis proefles — van kickboksen tot ju-jitsu, gebouwd om je mat vol te krijgen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor vechtsportschool",
    keywords: ["martial arts", "vechtsport", "vechtsportschool", "kickboksen", "bjj", "judo", "mma"],
    image: "https://images.unsplash.com/photo-1656653121475-e33829581294?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Sporters tijdens een training in een vechtsportschool.",
  },
  {
    slug: "crossfit-box",
    icon: "crossfitBox",
    group: "Fitness",
    title: "CrossFit-box",
    description:
      "Een stoere site met WOD's, coaches, roosters en een gratis intro — laat de community en resultaten nieuwe leden overtuigen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor CrossFit-box",
    keywords: ["crossfit", "crossfit box", "functional training", "bootcamp", "wod", "fitness"],
    image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Sporters tijdens een intensieve crossfit-training met halters.",
  },
  {
    slug: "music-school",
    icon: "musicSchool",
    group: "Onderwijs",
    title: "Muziekschool",
    description:
      "Een heldere site met instrumenten, docenten, lesvormen en online aanmelden — van eerste pianoles tot bandcoaching, vol roosters gegarandeerd.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor muziekschool",
    keywords: ["music school", "muziekschool", "muziekles", "pianoles", "gitaarles", "zangles"],
    image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een muziekles met een leerling achter een piano.",
  },
  {
    slug: "tutoring",
    icon: "tutoring",
    group: "Onderwijs",
    title: "Bijles & huiswerkbegeleiding",
    description:
      "Toon vakken, tarieven, resultaten en een snelle aanmelding — geef ouders vertrouwen en vul je agenda met gemotiveerde leerlingen.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor bijles of huiswerkbegeleiding",
    keywords: ["tutoring", "bijles", "huiswerkbegeleiding", "examentraining", "studiebegeleiding"],
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een leerling die geconcentreerd studeert met boeken en laptop.",
  },
  {
    slug: "cooking-studio",
    icon: "cookingStudio",
    group: "Onderwijs",
    title: "Kookstudio",
    description:
      "Een smaakvolle site met workshops, thema-avonden, groepsboekingen en online reserveren — van teamuitje tot kookcursus, zo geboekt.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor kookstudio",
    keywords: ["cooking class", "kookstudio", "kookworkshop", "kookcursus", "workshop koken", "culinair"],
    image: "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Deelnemers aan een kookworkshop in een professionele keuken.",
  },
  {
    slug: "psychologist",
    icon: "psychologist",
    group: "Zorg",
    title: "Psychologenpraktijk",
    description:
      "Een rustige, vertrouwde site met behandelingen, werkwijze, vergoedingen en een aanmeldformulier — drempelvrij de eerste stap zetten.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor psychologenpraktijk",
    keywords: ["psychologist", "psycholoog", "psychologenpraktijk", "therapie", "ggz", "coaching"],
    image: "https://images.unsplash.com/photo-1551847677-dc82d764e1eb?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een rustig gesprek tussen psycholoog en cliënt in de praktijk.",
  },
  {
    slug: "event-planner",
    icon: "eventPlanner",
    group: "Overig",
    title: "Evenementenbureau",
    description:
      "Een sprankelende site met diensten, eerdere events en een offerte-aanvraag — van bedrijfsfeest tot bruiloft, in een paar klikken geregeld.",
    ctaLabel: "Vraag deze website aan",
    projectType: "Website voor evenementenbureau",
    keywords: ["event", "evenementenbureau", "eventbureau", "feest", "bedrijfsevent", "bruiloft"],
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=720&q=80",
    imageAlt: "Een sfeervol ingerichte evenementenzaal klaar voor gasten.",
  },
] as const satisfies readonly LocalBusiness[];
