import type { IconType } from "react-icons";
import {
  LuActivity,
  LuBaby,
  LuBath,
  LuBriefcase,
  LuBrush,
  LuBug,
  LuBookOpenText,
  LuBuilding2,
  LuCalculator,
  LuCamera,
  LuCar,
  LuChefHat,
  LuCoffee,
  LuCroissant,
  LuDog,
  LuDroplet,
  LuDroplets,
  LuDumbbell,
  LuFlower,
  LuFlower2,
  LuGem,
  LuGraduationCap,
  LuHand,
  LuHardHat,
  LuHeartPulse,
  LuHouse,
  LuKeyRound,
  LuLanguages,
  LuPaintRoller,
  LuPawPrint,
  LuPen,
  LuPill,
  LuPlane,
  LuPlug,
  LuSandwich,
  LuScale,
  LuScissors,
  LuScissorsLineDashed,
  LuShieldCheck,
  LuShirt,
  LuShoppingBag,
  LuShoppingCart,
  LuSmartphone,
  LuSmile,
  LuSofa,
  LuSparkles,
  LuSprayCan,
  LuStamp,
  LuStethoscope,
  LuTrafficCone,
  LuTrees,
  LuUtensils,
  LuWarehouse,
  LuWrench,
  // Added categories (≥6 per filter)
  LuBicepsFlexed,
  LuBrain,
  LuCircleDot,
  LuClipboardCheck,
  LuCookingPot,
  LuFootprints,
  LuIceCreamCone,
  LuMegaphone,
  LuMusic,
  LuPartyPopper,
  LuPencilRuler,
  LuPersonStanding,
  LuPiggyBank,
  LuSwords,
} from "react-icons/lu";

import type { LocalBusinessIconName, LocalBusinessIconProps } from "@/types";

/**
 * Single source of truth mapping each business category to a Lucide icon.
 * Typed as a full Record so TypeScript fails the build if a category in
 * LocalBusinessIconName is ever missing an icon.
 */
const ICONS: Record<LocalBusinessIconName, IconType> = {
  // Auto
  carWash: LuDroplets,
  autoRepair: LuWrench,
  carDetailing: LuSprayCan,
  autoDealer: LuCar,
  drivingSchool: LuTrafficCone,
  tireService: LuCircleDot,
  // Vastgoed
  realEstate: LuHouse,
  propertyManagement: LuBuilding2,
  rentalAgency: LuKeyRound,
  commercialProperty: LuWarehouse,
  mortgageAdvisor: LuPiggyBank,
  homeInspector: LuClipboardCheck,
  // Horeca & food
  restaurant: LuUtensils,
  coffeeBar: LuCoffee,
  bakery: LuCroissant,
  fastFood: LuSandwich,
  catering: LuChefHat,
  iceCreamShop: LuIceCreamCone,
  // Beauty & wellness
  hairSalon: LuScissors,
  barbershop: LuScissorsLineDashed,
  beautySalon: LuSparkles,
  spa: LuBath,
  nailSalon: LuHand,
  pedicure: LuFootprints,
  // Zakelijke diensten
  lawyer: LuScale,
  accountant: LuCalculator,
  consultant: LuBriefcase,
  insurance: LuShieldCheck,
  notary: LuStamp,
  marketingAgency: LuMegaphone,
  // Huis & klus
  plumber: LuDroplet,
  electrician: LuPlug,
  cleaningService: LuBrush,
  pestControl: LuBug,
  landscaping: LuTrees,
  painter: LuPaintRoller,
  construction: LuHardHat,
  // Retail
  clothingStore: LuShoppingBag,
  mensFashion: LuShirt,
  electronicsStore: LuSmartphone,
  furnitureStore: LuSofa,
  supermarket: LuShoppingCart,
  jewelry: LuGem,
  flowerShop: LuFlower2,
  // Fitness
  gym: LuDumbbell,
  yogaStudio: LuFlower,
  personalTrainer: LuHeartPulse,
  danceStudio: LuPersonStanding,
  martialArts: LuSwords,
  crossfitBox: LuBicepsFlexed,
  // Onderwijs
  school: LuGraduationCap,
  languageCenter: LuLanguages,
  trainingCenter: LuBookOpenText,
  musicSchool: LuMusic,
  tutoring: LuPencilRuler,
  cookingStudio: LuCookingPot,
  // Zorg
  clinic: LuStethoscope,
  pharmacy: LuPill,
  physiotherapy: LuActivity,
  veterinary: LuPawPrint,
  dentist: LuSmile,
  psychologist: LuBrain,
  // Overig
  photographer: LuCamera,
  travelAgency: LuPlane,
  petStore: LuDog,
  childcare: LuBaby,
  tattooStudio: LuPen,
  eventPlanner: LuPartyPopper,
};

export function LocalBusinessIcon({ name }: LocalBusinessIconProps) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon aria-hidden="true" strokeWidth={1.6} />;
}
